language: script

env:
  global:
     CF_TARGET_URL="https://api.ng.bluemix.net"

services:
  - docker

script: bash -n *.sh


deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy_rollup.sh
    on:
      all_branches: true
